### ISSUE TITLE
Assignment 2 Demo Friday 5:30 PM

### ISSUE THREAD

**Issue by pigfly** [pigfly/RMIT-CSIT-RAD#2]
write down your student number and name in the comments. FIFO

**Comment by suuuukkkkkkk** [comment]
s3512592 Chao Geng

**Comment by rmit-s3525667-stee-pon** [comment]
s3525667 St Ee Pon

**Comment by moon-jung** [comment]
s3467941 Moonyoung Jung

**Comment by rmit-s3608452-Doan-QuangMinh** [comment]
s3608452 Doan Quang Minh

**Comment by suuuukkkkkkk** [comment]
s3635394 HU JUNJIAN

**Comment by ChenLaylaa** [comment]
s3499257 Chen Wei

**Comment by s3485566** [comment]
s3485566 Michael Guyatt

**Comment by moon-jung** [comment]
s3629911 Linjin Wang

**Comment by s3659076** [comment]
s3659076 Andrew Lay

**Comment by camillarueger** [comment]
s3713293 Camilla Jepsen

**Comment by Linhngg** [comment]
s3577273 Linh Tung Nguyen

**Comment by rmit-s3539505-marcel-nowosiak** [comment]
s3539505 Marcel Nowosiak

**Comment by KeeZikuan** [comment]
s3612148 Kee Zikuan

**Comment by s3542733** [comment]
s3542733 Sotoam Bak

**Comment by rmit-s3544333-mai-moua** [comment]
s3544333 Mai-Doua Moua

**Comment by yestinlin** [comment]
s3568499 mingyinglin

**Comment by caseyyan1104** [comment]
s3679535 Yan Qiannan

**Comment by yestinlin** [comment]
s3568499 mingyinglin

**Comment by amarotta97** [comment]
s3602839 Adrian Marotta

**Comment by space-bits** [comment]
S3433096 Rob Laine-Wyllie

**Comment by Fauxtography** [comment]
S3502921 Gabriel Haines

**Comment by smokker875** [comment]
s3536258 Qitong Nie

**Comment by s3649482** [comment]
s3649482 Khye Nyin Ku

**Comment by brianchenrmit** [comment]
s3600110 Brian Chen

**Comment by s3581649** [comment]
s3581649 Chang Sheng Lim

**Comment by XiaotingF** [comment]
s3626819 Xiaoting Fang

**Comment by chocolate2395** [comment]
s3455658 Tsang Charyl

**Comment by brianchenrmit** [comment]
s3600110 Brian Chen

**Comment by rmit-s3603463-stuart-wood** [comment]
s3603463 Stuart Wood

**Comment by s3601178** [comment]
s3601178 Simon Lu

**Comment by s35644242** [comment]
s3564424 April Rose Canete

**Comment by rmit-s3482002-daeyong-kim** [comment]
s3482002 Dae Yong kim

**Comment by rmit-s3603463-stuart-wood** [comment]
s3603463 Stuart Wood

**Comment by s3601178** [comment]
s3601178 Simon Lu

**Comment by JacobHarvey94** [comment]
s3529664 Jacob Harvey
